# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hvac_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12hvac_service.proto\x12\x0fhvac_service.v1\"/\n\x18SetTemperatureRequestMsg\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\"0\n\x19SetTemperatureResponseMsg\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\"\x07\n\x05OnMsg\"\x0c\n\nOnResponse\"\x08\n\x06OffMsg\"\r\n\x0bOffResponse2\xef\x01\n\x0bHVACService\x12g\n\x0eSetTemperature\x12).hvac_service.v1.SetTemperatureRequestMsg\x1a*.hvac_service.v1.SetTemperatureResponseMsg\x12\x39\n\x02On\x12\x16.hvac_service.v1.OnMsg\x1a\x1b.hvac_service.v1.OnResponse\x12<\n\x03Off\x12\x17.hvac_service.v1.OffMsg\x1a\x1c.hvac_service.v1.OffResponseb\x06proto3')



_SETTEMPERATUREREQUESTMSG = DESCRIPTOR.message_types_by_name['SetTemperatureRequestMsg']
_SETTEMPERATURERESPONSEMSG = DESCRIPTOR.message_types_by_name['SetTemperatureResponseMsg']
_ONMSG = DESCRIPTOR.message_types_by_name['OnMsg']
_ONRESPONSE = DESCRIPTOR.message_types_by_name['OnResponse']
_OFFMSG = DESCRIPTOR.message_types_by_name['OffMsg']
_OFFRESPONSE = DESCRIPTOR.message_types_by_name['OffResponse']
SetTemperatureRequestMsg = _reflection.GeneratedProtocolMessageType('SetTemperatureRequestMsg', (_message.Message,), {
  'DESCRIPTOR' : _SETTEMPERATUREREQUESTMSG,
  '__module__' : 'hvac_service_pb2'
  # @@protoc_insertion_point(class_scope:hvac_service.v1.SetTemperatureRequestMsg)
  })
_sym_db.RegisterMessage(SetTemperatureRequestMsg)

SetTemperatureResponseMsg = _reflection.GeneratedProtocolMessageType('SetTemperatureResponseMsg', (_message.Message,), {
  'DESCRIPTOR' : _SETTEMPERATURERESPONSEMSG,
  '__module__' : 'hvac_service_pb2'
  # @@protoc_insertion_point(class_scope:hvac_service.v1.SetTemperatureResponseMsg)
  })
_sym_db.RegisterMessage(SetTemperatureResponseMsg)

OnMsg = _reflection.GeneratedProtocolMessageType('OnMsg', (_message.Message,), {
  'DESCRIPTOR' : _ONMSG,
  '__module__' : 'hvac_service_pb2'
  # @@protoc_insertion_point(class_scope:hvac_service.v1.OnMsg)
  })
_sym_db.RegisterMessage(OnMsg)

OnResponse = _reflection.GeneratedProtocolMessageType('OnResponse', (_message.Message,), {
  'DESCRIPTOR' : _ONRESPONSE,
  '__module__' : 'hvac_service_pb2'
  # @@protoc_insertion_point(class_scope:hvac_service.v1.OnResponse)
  })
_sym_db.RegisterMessage(OnResponse)

OffMsg = _reflection.GeneratedProtocolMessageType('OffMsg', (_message.Message,), {
  'DESCRIPTOR' : _OFFMSG,
  '__module__' : 'hvac_service_pb2'
  # @@protoc_insertion_point(class_scope:hvac_service.v1.OffMsg)
  })
_sym_db.RegisterMessage(OffMsg)

OffResponse = _reflection.GeneratedProtocolMessageType('OffResponse', (_message.Message,), {
  'DESCRIPTOR' : _OFFRESPONSE,
  '__module__' : 'hvac_service_pb2'
  # @@protoc_insertion_point(class_scope:hvac_service.v1.OffResponse)
  })
_sym_db.RegisterMessage(OffResponse)

_HVACSERVICE = DESCRIPTOR.services_by_name['HVACService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETTEMPERATUREREQUESTMSG._serialized_start=39
  _SETTEMPERATUREREQUESTMSG._serialized_end=86
  _SETTEMPERATURERESPONSEMSG._serialized_start=88
  _SETTEMPERATURERESPONSEMSG._serialized_end=136
  _ONMSG._serialized_start=138
  _ONMSG._serialized_end=145
  _ONRESPONSE._serialized_start=147
  _ONRESPONSE._serialized_end=159
  _OFFMSG._serialized_start=161
  _OFFMSG._serialized_end=169
  _OFFRESPONSE._serialized_start=171
  _OFFRESPONSE._serialized_end=184
  _HVACSERVICE._serialized_start=187
  _HVACSERVICE._serialized_end=426
# @@protoc_insertion_point(module_scope)
